---
dist: bionic
services:
  - docker

language: python
python:
  - "3.7"

env:
  - distribution: centos-8
  - distribution: centos-7
  - distribution: centos-6
  - distribution: fedora-32
  - distribution: fedora-31
  - distribution: fedora-30
  - distribution: fedora-29
  - distribution: fedora-28
  - distribution: fedora-27
  - distribution: fedora-26
  - distribution: ubuntu-20.04
  - distribution: ubuntu-18.04
  - distribution: ubuntu-16.04
  - distribution: debian-10
  - distribution: debian-9
  - distribution: debian-8
  - distribution: oraclelinux-8
  - distribution: oraclelinux-7
  - distribution: oraclelinux-6
  - distribution: amazonlinux-2
  - distribution: amazonlinux-1
  - distribution: opensuse-leap
  - distribution: opensuse-tumbleweed
  - distribution: opensuse-13.2
  - distribution: opensuse-15
  - distribution: opensuse-15.1
  - distribution: archlinux-rolling

before_install:
  - 'docker pull diodonfrost/${distribution}-ansible:latest'

install:
  - pip install ansible==2.9.4 molecule==3.0.2 docker==4.2.2

script:
  - distribution=${distribution} molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
