---
dist: xenial
services:
  - docker

env:
#-----------------------------------------------
#
# CentOS
#
#-----------------------------------------------
  - distribution: centos-8
  - distribution: centos-7
  - distribution: centos-6

#--------------------------------
#
# Fedora
#
#--------------------------------
  - distribution: fedora-32
  - distribution: fedora-31
  - distribution: fedora-30
  - distribution: fedora-29
  - distribution: fedora-28
  - distribution: fedora-27
  - distribution: fedora-26

#--------------------------------
#
# Ubuntu
#
#--------------------------------
  - distribution: ubuntu-20.04
  - distribution: ubuntu-20.04
  - distribution: ubuntu-18.04
  - distribution: ubuntu-16.04

#--------------------------------
#
# Debian
#
#--------------------------------
  - distribution: debian-10
  - distribution: debian-9
  - distribution: debian-8

#--------------------------------
#
# Oraclelinux
#
#--------------------------------
  - distribution: oraclelinux-8
  - distribution: oraclelinux-7
  - distribution: oraclelinux-6

#--------------------------------
#
# Amazonlinux
#
#--------------------------------
  - distribution: amazonlinux-2
  - distribution: amazonlinux-1

#--------------------------------
#
# Opensuse
#
#--------------------------------
  - distribution: opensuse-13.2

before_install:
  # Build docker container
  - 'sudo docker pull diodonfrost/${distribution}-ansible:latest'

script:
  - container_id=$(mktemp)

  # Run container and mount ansible role with it
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /dev/fuse:/dev/fuse --volume="${PWD}":/etc/ansible/roles/ansible-role-amazon-ssm:ro diodonfrost/${distribution}-ansible:latest > "${container_id}"'

  # Check syntax
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-amazon-ssm/tests/test.yml --syntax-check'

  # Run ansible playbook
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-amazon-ssm/tests/test.yml'

  # Test indempotence
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-amazon-ssm/tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test role
  - 'inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})'

  # Delete container
  - 'sudo docker rm -f "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
