---
# Install aws ssm agent on Windows family system

- name: Windows | Install aws ssm agent
  win_package:
    path: "{{ ssm_package_url }}"
    product_id: amazon-ssm-agent
    creates_path: C:\Program Files\Amazon\SSM\amazon-ssm-agent.exe
    arguments: /S
    state: present


- name: Windows | Manage aws ssm agent service
  win_service:
    name: "{{ ssm_service }}"
    start_mode: auto
    state: started
