---
# handlers file for ansible-role-amazon-ssm

- name: Linux systemd reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Linux | Restart amazon ssm agent
  ansible.builtin.service:
    name: "{{ ssm_service }}"
    state: restarted

- name: Darwin | Restart amazon ssm agent
  launchd:
    name: "{{ ssm_service }}"
    state: restarted

- name: Windows | Restart amazon ssm agent
  ansible.windows.win_service:
    name: "{{ ssm_service }}"
    state: restarted
